global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']